name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: npm install
    - name: run test
      run: npm run test
    - name: login to Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t rama402/hello-world-react .
    - name: push the image to Dockerhub
      run: docker push rama402/hello-world-react:latest
      

